### ISSUE TITLE
infinite loop in constructor when bounding box array contains Infinity

### ISSUE THREAD

**Issue by jcphill** [DanielJDufour/geo-extent#9]
The GeoExtent constructor will send preciso divide into an infinite loop if the input bounds contain Infinity.

The debugger shows dividend = "NaNNaNNaNNaNNaNNaNNaNNaN.4430805326" so a number is being treated as a string.

The looping call is through avg, which converts its arguments to strings at https://github.com/DanielJDufour/geo-extent/blob/4b7a27b3ea99f4b50c50acfb5edda1cc98bc8024/src/geo-extent.js#L20

In my case the constructor is called by reproj, which throws an error if some(isNaN) but should maybe be ! all(isFinite) instead at https://github.com/DanielJDufour/geo-extent/blob/4b7a27b3ea99f4b50c50acfb5edda1cc98bc8024/src/geo-extent.js#L437

**Comment by DanielJDufour** [comment]
Thanks for catching this! Would you happen to be able to provide the full bbox that caused this? ... and I can add it as a test case to geo-extent.

Also, wondering if there are situations where geo-extent might want to support a bbox with infinity values?  Is there any valid use case you are aware of for this?

In theory, I think such a bbox can exist, but the Math might get complicated...err I mean fun

**Comment by jcphill** [comment]
I was seeing it on:
`    new GeoExtent([166021.4430805326, 0, Infinity, Infinity], { srs: "EPSG:26916" });`

The latest georaster-layer-for-leaflet and geo-extent versions don't trigger the issue in the same way.

**Comment by DanielJDufour** [comment]
I just pushed some changes that partially solve this issue.   When a user runs:
```js
new GeoExtent([166021.4430805326, 0, Infinity, Infinity], { srs: "EPSG:26916" })
```
The following class instance is now returned:
```js
GeoExtent {
  srs: 'EPSG:26916',
  xmin: 166021.4430805326,
  xmin_str: '166021.4430805326',
  ymin: 0,
  ymin_str: '0',
  xmax: Infinity,
  xmax_str: 'Infinity',
  ymax: Infinity,
  ymax_str: 'Infinity',
  width_str: 'Infinity',
  width: Infinity,
  height_str: 'Infinity',
  height: Infinity,
  bottomLeft: { x: 166021.4430805326, y: 0 },
  bottomRight: { x: Infinity, y: 0 },
  topLeft: { x: 166021.4430805326, y: Infinity },
  topRight: { x: Infinity, y: Infinity },
  leafletBounds: [ [ 0, 166021.4430805326 ], [ Infinity, Infinity ] ],
  area_str: 'Infinity',
  area: Infinity,
  perimeter_str: 'Infinity',
  perimeter: Infinity,
  bbox: [ 166021.4430805326, 0, Infinity, Infinity ],
  bbox_str: [ '166021.4430805326', '0', 'Infinity', 'Infinity' ],
  center_str: { x: 'Infinity', y: 'Infinity' },
  center: { x: Infinity, y: Infinity },
  str: '166021.4430805326,0,Infinity,Infinity',
  wkt: 'POLYGON((Infinity 0,Infinity Infinity,166021.4430805326 Infinity,166021.4430805326 0,Infinity 0))',
  ewkt: 'SRID=26916;POLYGON((Infinity 0,Infinity Infinity,166021.4430805326 Infinity,166021.4430805326 0,Infinity 0))',
  js: 'new GeoExtent([166021.4430805326, 0, Infinity, Infinity], { srs: "EPSG:26916" })'
}
```

**Comment by DanielJDufour** [comment]
I'd like to add the isFinite check that you proposed and also add a test case along with it.  Would you be able to provide the original extent you tried to reproject to 26916?

**Comment by jcphill** [comment]
EPSG:3857 [-10018754.171394622, -7.081154551613622e-10, 0, 10018754.171394624]

**Comment by DanielJDufour** [comment]
Thank you! I published a new version of geo-extent that addresses this scenario.  Please see this test for usage:
https://github.com/DanielJDufour/geo-extent/blob/main/test/test.reproj.js#L113

Basically, it'll now throw an error if infinity values are present.  But a user can pass in allow_infinity=true if for whatever reason they are okay with infinity values.

**Comment by DanielJDufour** [comment]
I'll close this issue now, but please do continue to alert me to bugs and edge cases!  It's really helpful :-)
